name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.NOQ_LIGHTSAIL_SSH_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.DEMO_LIGHTSAIL_STATIC_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh ubuntu@${{ secrets.DEMO_LIGHTSAIL_STATIC_IP }} "echo 'SSH connection successful!'"

    - name: Print Success Message
      run: echo "SSH connection tested successfully!"
